# Ignore vendored test fixtures & examples to avoid false positives
# (z.B. Test-Keys in Dependencies). Wir löschen nichts aus vendor/,
# damit Cargo-Checksummen intakt bleiben.
paths-ignore:
  - "vendor/**/tests/**"
  - "vendor/**/testdata/**"
  - "vendor/**/fixtures/**"
  - "vendor/**/examples/**"
  - "vendor/**/example/**"

# Optional: eigene Pfade für lokale Tests/Demos
# - "crates/**/tests/fixtures/**"
